# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
#Error (line 20): the step 'PublishTestResults@2' does not have a conversion path yet
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Permissions
      run: chmod -R 755 ./
      shell: sh
    - name: Resolve Dependencies
      run: ./mvn.command
      shell: sh
    - name: Execute CITS Test
      run: ./Run.command -run -project_location "Projects/TestProject" -release "MyRelease" -testset "Regression" -setEnv "run.ExecutionMode=Grid" -setEnv "run.RemoteGridURL=https://nehadeshmukh_rsUbqj:b7y1ExMZspHZyJc1pHV7@hub-cloud.browserstack.com/wd/hub"
      shell: sh
    - # "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
      name: Publish Reports
      run: |
        echo "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
        #task: PublishTestResults@2
        #displayName: Publish Reports
        #inputs:
        #  testresultsformat: NUnit
        #  testresultsfiles: Projects/TestProject/Results/TestExecution/MyRelease/Regression/Latest/azure.xml
        #  failtaskonfailedtests: true
        #  testruntitle: Test Run
        #  publishrunattachments: true
                    
